/**
 * @fileoverview
 * This file contains an example of the V3 score format (tick-based event stream).
 * It was generated by converting the V2 score 'combined-4-midi.json' as part
 * of the performance upgrade initiative.
 *
 * This data structure is optimized for efficient playback, as the engine can
 * process events at their exact tick without iterating through the entire score.
 */
export const v3EventStreamExample = {
  "version": "3.0",
  "ppq": 10080,
  "metadata": {
    "id": "combined-4-midi",
    "title": "combined_4-MIDI",
    "displayTitle": "combined_4-MIDI",
    "sourceType": "midi",
    "originalFormat": "midi",
    "fileName": "combined_4.mid",
    "importedFrom": "file:///C:/music_work/combined_4.mid",
    "migratedAt": "2026-05-10T13:32:23.357Z",
    "visualMapping": {
      "strategy": "nearest-project-key-preserve-midi-frequency",
      "source": "combined_4.mid",
      "keyRange": "C3-B5",
      "note": "Audio keeps the original MIDI frequency and timing. The visual key is the nearest available project piano key.",
      "stats": {
        "total": 1623,
        "exactNatural": 689,
        "nearestMapped": 934,
        "clampedLow": 110,
        "clampedHigh": 170,
        "minMidi": 37,
        "maxMidi": 97,
        "keyUsage": {
          "z": 119,
          "x": 12,
          "c": 62,
          "v": 35,
          "b": 7,
          "n": 16,
          "m": 122,
          "a": 31,
          "s": 70,
          "d": 103,
          "f": 101,
          "g": 71,
          "h": 50,
          "j": 180,
          "q": 41,
          "w": 67,
          "e": 96,
          "r": 101,
          "t": 41,
          "y": 26,
          "u": 272
        }
      }
    }
  },
  "events": [
    {
      "tick": 0,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 0,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 0,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 5040,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 5040,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 10080,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 10080,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 15120,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 15120,
      "type": "note_on",
      "note": 85,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 20160,
      "type": "note_off",
      "note": 85,
      "trackId": 1
    },
    {
      "tick": 20160,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 25200,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 25200,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 30240,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 30240,
      "type": "note_off",
      "note": 66,
      "trackId": 2
    },
    {
      "tick": 30240,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 30240,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 30240,
      "type": "note_on",
      "note": 52,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 30240,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 35280,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 35280,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 40320,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 40320,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 45360,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 45360,
      "type": "note_on",
      "note": 88,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 50400,
      "type": "note_off",
      "note": 88,
      "trackId": 1
    },
    {
      "tick": 50400,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 55440,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 55440,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 60480,
      "type": "note_off",
      "note": 52,
      "trackId": 2
    },
    {
      "tick": 60480,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 60480,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 60480,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 60480,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 60480,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 65520,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 65520,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 70560,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 70560,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 75600,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 75600,
      "type": "note_on",
      "note": 85,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 80640,
      "type": "note_off",
      "note": 85,
      "trackId": 1
    },
    {
      "tick": 80640,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 85680,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 85680,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 90720,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 90720,
      "type": "note_off",
      "note": 66,
      "trackId": 2
    },
    {
      "tick": 90720,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 90720,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 90720,
      "type": "note_on",
      "note": 52,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 90720,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 95760,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 95760,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 100800,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 100800,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 105840,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 105840,
      "type": "note_on",
      "note": 88,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 110880,
      "type": "note_off",
      "note": 88,
      "trackId": 1
    },
    {
      "tick": 110880,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 115920,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 115920,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 120960,
      "type": "note_off",
      "note": 52,
      "trackId": 2
    },
    {
      "tick": 120960,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 120960,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 120960,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 120960,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 120960,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 126000,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 126000,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 131040,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 131040,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 136080,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 136080,
      "type": "note_off",
      "note": 66,
      "trackId": 2
    },
    {
      "tick": 136080,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 136080,
      "type": "note_on",
      "note": 85,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 136080,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 136080,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 141120,
      "type": "note_off",
      "note": 85,
      "trackId": 1
    },
    {
      "tick": 141120,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 146160,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 146160,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 151200,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 151200,
      "type": "note_off",
      "note": 66,
      "trackId": 2
    },
    {
      "tick": 151200,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 151200,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 151200,
      "type": "note_on",
      "note": 52,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 151200,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 156240,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 156240,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 161280,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 161280,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 166320,
      "type": "note_off",
      "note": 52,
      "trackId": 2
    },
    {
      "tick": 166320,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 166320,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 166320,
      "type": "note_on",
      "note": 88,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 166320,
      "type": "note_on",
      "note": 52,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 166320,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 171360,
      "type": "note_off",
      "note": 88,
      "trackId": 1
    },
    {
      "tick": 171360,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 176400,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 176400,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 181440,
      "type": "note_off",
      "note": 52,
      "trackId": 2
    },
    {
      "tick": 181440,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 181440,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 181440,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 181440,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 181440,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 186480,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 186480,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 191520,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 191520,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 196560,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 196560,
      "type": "note_off",
      "note": 66,
      "trackId": 2
    },
    {
      "tick": 196560,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 196560,
      "type": "note_on",
      "note": 85,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 196560,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 196560,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 201600,
      "type": "note_off",
      "note": 85,
      "trackId": 1
    },
    {
      "tick": 201600,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 206640,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 206640,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 211680,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 211680,
      "type": "note_off",
      "note": 66,
      "trackId": 2
    },
    {
      "tick": 211680,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 211680,
      "type": "note_on",
      "note": 87,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 211680,
      "type": "note_on",
      "note": 52,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 211680,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 216720,
      "type": "note_off",
      "note": 87,
      "trackId": 1
    },
    {
      "tick": 216720,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 221760,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 221760,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 226800,
      "type": "note_off",
      "note": 52,
      "trackId": 2
    },
    {
      "tick": 226800,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 226800,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 226800,
      "type": "note_on",
      "note": 88,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 226800,
      "type": "note_on",
      "note": 52,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 226800,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 231840,
      "type": "note_off",
      "note": 88,
      "trackId": 1
    },
    {
      "tick": 231840,
      "type": "note_on",
      "note": 78,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 236880,
      "type": "note_off",
      "note": 78,
      "trackId": 1
    },
    {
      "tick": 236880,
      "type": "note_on",
      "note": 83,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 241920,
      "type": "note_off",
      "note": 83,
      "trackId": 1
    },
    {
      "tick": 241920,
      "type": "note_on",
      "note": 63,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 241920,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 241920,
      "type": "note_on",
      "note": 71,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 241920,
      "type": "note_on",
      "note": 47,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 241920,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 241920,
      "type": "note_off",
      "note": 52,
      "trackId": 2
    },
    {
      "tick": 241920,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 257040,
      "type": "note_off",
      "note": 63,
      "trackId": 1
    },
    {
      "tick": 257040,
      "type": "note_off",
      "note": 66,
      "trackId": 1
    },
    {
      "tick": 257040,
      "type": "note_off",
      "note": 71,
      "trackId": 1
    },
    {
      "tick": 257040,
      "type": "note_on",
      "note": 63,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 257040,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 257040,
      "type": "note_on",
      "note": 71,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 267120,
      "type": "note_off",
      "note": 63,
      "trackId": 1
    },
    {
      "tick": 267120,
      "type": "note_off",
      "note": 66,
      "trackId": 1
    },
    {
      "tick": 267120,
      "type": "note_off",
      "note": 71,
      "trackId": 1
    },
    {
      "tick": 267120,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 272160,
      "type": "note_off",
      "note": 47,
      "trackId": 2
    },
    {
      "tick": 272160,
      "type": "note_off",
      "note": 59,
      "trackId": 2
    },
    {
      "tick": 272160,
      "type": "note_off",
      "note": 59,
      "trackId": 1
    },
    {
      "tick": 272160,
      "type": "note_on",
      "note": 64,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 272160,
      "type": "note_on",
      "note": 68,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 272160,
      "type": "note_on",
      "note": 71,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 272160,
      "type": "note_on",
      "note": 40,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 272160,
      "type": "note_on",
      "note": 52,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 287280,
      "type": "note_off",
      "note": 64,
      "trackId": 1
    },
    {
      "tick": 287280,
      "type": "note_off",
      "note": 68,
      "trackId": 1
    },
    {
      "tick": 287280,
      "type": "note_off",
      "note": 71,
      "trackId": 1
    },
    {
      "tick": 287280,
      "type": "note_on",
      "note": 64,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 287280,
      "type": "note_on",
      "note": 68,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 287280,
      "type": "note_on",
      "note": 71,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 297360,
      "type": "note_off",
      "note": 64,
      "trackId": 1
    },
    {
      "tick": 297360,
      "type": "note_off",
      "note": 68,
      "trackId": 1
    },
    {
      "tick": 297360,
      "type": "note_off",
      "note": 71,
      "trackId": 1
    },
    {
      "tick": 297360,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 302399,
      "type": "note_off",
      "note": 40,
      "trackId": 2
    },
    {
      "tick": 302400,
      "type": "note_off",
      "note": 59,
      "trackId": 1
    },
    {
      "tick": 302400,
      "type": "note_off",
      "note": 52,
      "trackId": 2
    },
    {
      "tick": 302400,
      "type": "note_on",
      "note": 63,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 302400,
      "type": "note_on",
      "note": 66,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 302400,
      "type": "note_on",
      "note": 71,
      "velocity": 0.7086614173228346,
      "trackId": 1
    },
    {
      "tick": 302400,
      "type": "note_on",
      "note": 47,
      "velocity": 0.7086614173228346,
      "trackId": 2
    },
    {
      "tick": 302400,
      "type": "note_on",
      "note": 59,
      "velocity": 0.7086614173228346,
      "trackId": 2
    }
  ]
}

export default v3EventStreamExample;
